/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as piraWethSol from "./PiraWETH.sol";
export type { piraWethSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { PiraERC20 } from "./PiraERC20";
export type { PiraFactory } from "./PiraFactory";
export type { PiraPair } from "./PiraPair";
