/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface PiraZapV1Interface extends utils.Interface {
  functions: {
    "MAX_INT()": FunctionFragment;
    "MINIMUM_AMOUNT()": FunctionFragment;
    "PiraRouter()": FunctionFragment;
    "WBNB()": FunctionFragment;
    "estimateZapInRebalancingSwap(address,address,uint256,uint256,address)": FunctionFragment;
    "estimateZapInSwap(address,uint256,address)": FunctionFragment;
    "estimateZapOutSwap(address,uint256,address)": FunctionFragment;
    "maxZapReverseRatio()": FunctionFragment;
    "owner()": FunctionFragment;
    "recoverWrongTokens(address,uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateMaxZapInverseRatio(uint256)": FunctionFragment;
    "zapInBNB(address,uint256)": FunctionFragment;
    "zapInBNBRebalancing(address,uint256,address,uint256,uint256,bool)": FunctionFragment;
    "zapInToken(address,uint256,address,uint256)": FunctionFragment;
    "zapInTokenRebalancing(address,address,uint256,uint256,address,uint256,uint256,bool)": FunctionFragment;
    "zapOutBNB(address,uint256,uint256)": FunctionFragment;
    "zapOutToken(address,address,uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MAX_INT"
      | "MINIMUM_AMOUNT"
      | "PiraRouter"
      | "WBNB"
      | "estimateZapInRebalancingSwap"
      | "estimateZapInSwap"
      | "estimateZapOutSwap"
      | "maxZapReverseRatio"
      | "owner"
      | "recoverWrongTokens"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateMaxZapInverseRatio"
      | "zapInBNB"
      | "zapInBNBRebalancing"
      | "zapInToken"
      | "zapInTokenRebalancing"
      | "zapOutBNB"
      | "zapOutToken"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "MAX_INT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MINIMUM_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PiraRouter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "WBNB", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "estimateZapInRebalancingSwap",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "estimateZapInSwap",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "estimateZapOutSwap",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "maxZapReverseRatio",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recoverWrongTokens",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMaxZapInverseRatio",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "zapInBNB",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "zapInBNBRebalancing",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "zapInToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "zapInTokenRebalancing",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "zapOutBNB",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "zapOutToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "MAX_INT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MINIMUM_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PiraRouter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WBNB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "estimateZapInRebalancingSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateZapInSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateZapOutSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxZapReverseRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recoverWrongTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMaxZapInverseRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "zapInBNB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "zapInBNBRebalancing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "zapInToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "zapInTokenRebalancing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "zapOutBNB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "zapOutToken",
    data: BytesLike
  ): Result;

  events: {
    "AdminTokenRecovery(address,uint256)": EventFragment;
    "NewMaxZapReverseRatio(uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "ZapIn(address,address,uint256,uint256,address)": EventFragment;
    "ZapInRebalancing(address,address,address,uint256,uint256,uint256,address)": EventFragment;
    "ZapOut(address,address,uint256,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminTokenRecovery"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewMaxZapReverseRatio"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ZapIn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ZapInRebalancing"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ZapOut"): EventFragment;
}

export interface AdminTokenRecoveryEventObject {
  tokenAddress: string;
  amountTokens: BigNumber;
}
export type AdminTokenRecoveryEvent = TypedEvent<
  [string, BigNumber],
  AdminTokenRecoveryEventObject
>;

export type AdminTokenRecoveryEventFilter =
  TypedEventFilter<AdminTokenRecoveryEvent>;

export interface NewMaxZapReverseRatioEventObject {
  maxZapReverseRatio: BigNumber;
}
export type NewMaxZapReverseRatioEvent = TypedEvent<
  [BigNumber],
  NewMaxZapReverseRatioEventObject
>;

export type NewMaxZapReverseRatioEventFilter =
  TypedEventFilter<NewMaxZapReverseRatioEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface ZapInEventObject {
  tokenToZap: string;
  lpToken: string;
  tokenAmountIn: BigNumber;
  lpTokenAmountReceived: BigNumber;
  user: string;
}
export type ZapInEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, string],
  ZapInEventObject
>;

export type ZapInEventFilter = TypedEventFilter<ZapInEvent>;

export interface ZapInRebalancingEventObject {
  token0ToZap: string;
  token1ToZap: string;
  lpToken: string;
  token0AmountIn: BigNumber;
  token1AmountIn: BigNumber;
  lpTokenAmountReceived: BigNumber;
  user: string;
}
export type ZapInRebalancingEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber, BigNumber, string],
  ZapInRebalancingEventObject
>;

export type ZapInRebalancingEventFilter =
  TypedEventFilter<ZapInRebalancingEvent>;

export interface ZapOutEventObject {
  lpToken: string;
  tokenToReceive: string;
  lpTokenAmount: BigNumber;
  tokenAmountReceived: BigNumber;
  user: string;
}
export type ZapOutEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, string],
  ZapOutEventObject
>;

export type ZapOutEventFilter = TypedEventFilter<ZapOutEvent>;

export interface PiraZapV1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PiraZapV1Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MAX_INT(overrides?: CallOverrides): Promise<[BigNumber]>;

    MINIMUM_AMOUNT(overrides?: CallOverrides): Promise<[BigNumber]>;

    PiraRouter(overrides?: CallOverrides): Promise<[string]>;

    WBNB(overrides?: CallOverrides): Promise<[string]>;

    estimateZapInRebalancingSwap(
      _token0ToZap: PromiseOrValue<string>,
      _token1ToZap: PromiseOrValue<string>,
      _token0AmountIn: PromiseOrValue<BigNumberish>,
      _token1AmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        swapAmountIn: BigNumber;
        swapAmountOut: BigNumber;
        sellToken0: boolean;
      }
    >;

    estimateZapInSwap(
      _tokenToZap: PromiseOrValue<string>,
      _tokenAmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string] & {
        swapAmountIn: BigNumber;
        swapAmountOut: BigNumber;
        swapTokenOut: string;
      }
    >;

    estimateZapOutSwap(
      _lpToken: PromiseOrValue<string>,
      _lpTokenAmount: PromiseOrValue<BigNumberish>,
      _tokenToReceive: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string] & {
        swapAmountIn: BigNumber;
        swapAmountOut: BigNumber;
        swapTokenOut: string;
      }
    >;

    maxZapReverseRatio(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    recoverWrongTokens(
      _tokenAddress: PromiseOrValue<string>,
      _tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateMaxZapInverseRatio(
      _maxZapInverseRatio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    zapInBNB(
      _lpToken: PromiseOrValue<string>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    zapInBNBRebalancing(
      _token1ToZap: PromiseOrValue<string>,
      _token1AmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      _tokenAmountInMax: PromiseOrValue<BigNumberish>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      _isToken0Sold: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    zapInToken(
      _tokenToZap: PromiseOrValue<string>,
      _tokenAmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    zapInTokenRebalancing(
      _token0ToZap: PromiseOrValue<string>,
      _token1ToZap: PromiseOrValue<string>,
      _token0AmountIn: PromiseOrValue<BigNumberish>,
      _token1AmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      _tokenAmountInMax: PromiseOrValue<BigNumberish>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      _isToken0Sold: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    zapOutBNB(
      _lpToken: PromiseOrValue<string>,
      _lpTokenAmount: PromiseOrValue<BigNumberish>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    zapOutToken(
      _lpToken: PromiseOrValue<string>,
      _tokenToReceive: PromiseOrValue<string>,
      _lpTokenAmount: PromiseOrValue<BigNumberish>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  MAX_INT(overrides?: CallOverrides): Promise<BigNumber>;

  MINIMUM_AMOUNT(overrides?: CallOverrides): Promise<BigNumber>;

  PiraRouter(overrides?: CallOverrides): Promise<string>;

  WBNB(overrides?: CallOverrides): Promise<string>;

  estimateZapInRebalancingSwap(
    _token0ToZap: PromiseOrValue<string>,
    _token1ToZap: PromiseOrValue<string>,
    _token0AmountIn: PromiseOrValue<BigNumberish>,
    _token1AmountIn: PromiseOrValue<BigNumberish>,
    _lpToken: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, boolean] & {
      swapAmountIn: BigNumber;
      swapAmountOut: BigNumber;
      sellToken0: boolean;
    }
  >;

  estimateZapInSwap(
    _tokenToZap: PromiseOrValue<string>,
    _tokenAmountIn: PromiseOrValue<BigNumberish>,
    _lpToken: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, string] & {
      swapAmountIn: BigNumber;
      swapAmountOut: BigNumber;
      swapTokenOut: string;
    }
  >;

  estimateZapOutSwap(
    _lpToken: PromiseOrValue<string>,
    _lpTokenAmount: PromiseOrValue<BigNumberish>,
    _tokenToReceive: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, string] & {
      swapAmountIn: BigNumber;
      swapAmountOut: BigNumber;
      swapTokenOut: string;
    }
  >;

  maxZapReverseRatio(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  recoverWrongTokens(
    _tokenAddress: PromiseOrValue<string>,
    _tokenAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateMaxZapInverseRatio(
    _maxZapInverseRatio: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  zapInBNB(
    _lpToken: PromiseOrValue<string>,
    _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  zapInBNBRebalancing(
    _token1ToZap: PromiseOrValue<string>,
    _token1AmountIn: PromiseOrValue<BigNumberish>,
    _lpToken: PromiseOrValue<string>,
    _tokenAmountInMax: PromiseOrValue<BigNumberish>,
    _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
    _isToken0Sold: PromiseOrValue<boolean>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  zapInToken(
    _tokenToZap: PromiseOrValue<string>,
    _tokenAmountIn: PromiseOrValue<BigNumberish>,
    _lpToken: PromiseOrValue<string>,
    _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  zapInTokenRebalancing(
    _token0ToZap: PromiseOrValue<string>,
    _token1ToZap: PromiseOrValue<string>,
    _token0AmountIn: PromiseOrValue<BigNumberish>,
    _token1AmountIn: PromiseOrValue<BigNumberish>,
    _lpToken: PromiseOrValue<string>,
    _tokenAmountInMax: PromiseOrValue<BigNumberish>,
    _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
    _isToken0Sold: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  zapOutBNB(
    _lpToken: PromiseOrValue<string>,
    _lpTokenAmount: PromiseOrValue<BigNumberish>,
    _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  zapOutToken(
    _lpToken: PromiseOrValue<string>,
    _tokenToReceive: PromiseOrValue<string>,
    _lpTokenAmount: PromiseOrValue<BigNumberish>,
    _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    MAX_INT(overrides?: CallOverrides): Promise<BigNumber>;

    MINIMUM_AMOUNT(overrides?: CallOverrides): Promise<BigNumber>;

    PiraRouter(overrides?: CallOverrides): Promise<string>;

    WBNB(overrides?: CallOverrides): Promise<string>;

    estimateZapInRebalancingSwap(
      _token0ToZap: PromiseOrValue<string>,
      _token1ToZap: PromiseOrValue<string>,
      _token0AmountIn: PromiseOrValue<BigNumberish>,
      _token1AmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        swapAmountIn: BigNumber;
        swapAmountOut: BigNumber;
        sellToken0: boolean;
      }
    >;

    estimateZapInSwap(
      _tokenToZap: PromiseOrValue<string>,
      _tokenAmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string] & {
        swapAmountIn: BigNumber;
        swapAmountOut: BigNumber;
        swapTokenOut: string;
      }
    >;

    estimateZapOutSwap(
      _lpToken: PromiseOrValue<string>,
      _lpTokenAmount: PromiseOrValue<BigNumberish>,
      _tokenToReceive: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string] & {
        swapAmountIn: BigNumber;
        swapAmountOut: BigNumber;
        swapTokenOut: string;
      }
    >;

    maxZapReverseRatio(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    recoverWrongTokens(
      _tokenAddress: PromiseOrValue<string>,
      _tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateMaxZapInverseRatio(
      _maxZapInverseRatio: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    zapInBNB(
      _lpToken: PromiseOrValue<string>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    zapInBNBRebalancing(
      _token1ToZap: PromiseOrValue<string>,
      _token1AmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      _tokenAmountInMax: PromiseOrValue<BigNumberish>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      _isToken0Sold: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    zapInToken(
      _tokenToZap: PromiseOrValue<string>,
      _tokenAmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    zapInTokenRebalancing(
      _token0ToZap: PromiseOrValue<string>,
      _token1ToZap: PromiseOrValue<string>,
      _token0AmountIn: PromiseOrValue<BigNumberish>,
      _token1AmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      _tokenAmountInMax: PromiseOrValue<BigNumberish>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      _isToken0Sold: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    zapOutBNB(
      _lpToken: PromiseOrValue<string>,
      _lpTokenAmount: PromiseOrValue<BigNumberish>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    zapOutToken(
      _lpToken: PromiseOrValue<string>,
      _tokenToReceive: PromiseOrValue<string>,
      _lpTokenAmount: PromiseOrValue<BigNumberish>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AdminTokenRecovery(address,uint256)"(
      tokenAddress?: PromiseOrValue<string> | null,
      amountTokens?: null
    ): AdminTokenRecoveryEventFilter;
    AdminTokenRecovery(
      tokenAddress?: PromiseOrValue<string> | null,
      amountTokens?: null
    ): AdminTokenRecoveryEventFilter;

    "NewMaxZapReverseRatio(uint256)"(
      maxZapReverseRatio?: null
    ): NewMaxZapReverseRatioEventFilter;
    NewMaxZapReverseRatio(
      maxZapReverseRatio?: null
    ): NewMaxZapReverseRatioEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "ZapIn(address,address,uint256,uint256,address)"(
      tokenToZap?: PromiseOrValue<string> | null,
      lpToken?: PromiseOrValue<string> | null,
      tokenAmountIn?: null,
      lpTokenAmountReceived?: null,
      user?: PromiseOrValue<string> | null
    ): ZapInEventFilter;
    ZapIn(
      tokenToZap?: PromiseOrValue<string> | null,
      lpToken?: PromiseOrValue<string> | null,
      tokenAmountIn?: null,
      lpTokenAmountReceived?: null,
      user?: PromiseOrValue<string> | null
    ): ZapInEventFilter;

    "ZapInRebalancing(address,address,address,uint256,uint256,uint256,address)"(
      token0ToZap?: PromiseOrValue<string> | null,
      token1ToZap?: PromiseOrValue<string> | null,
      lpToken?: null,
      token0AmountIn?: null,
      token1AmountIn?: null,
      lpTokenAmountReceived?: null,
      user?: PromiseOrValue<string> | null
    ): ZapInRebalancingEventFilter;
    ZapInRebalancing(
      token0ToZap?: PromiseOrValue<string> | null,
      token1ToZap?: PromiseOrValue<string> | null,
      lpToken?: null,
      token0AmountIn?: null,
      token1AmountIn?: null,
      lpTokenAmountReceived?: null,
      user?: PromiseOrValue<string> | null
    ): ZapInRebalancingEventFilter;

    "ZapOut(address,address,uint256,uint256,address)"(
      lpToken?: PromiseOrValue<string> | null,
      tokenToReceive?: PromiseOrValue<string> | null,
      lpTokenAmount?: null,
      tokenAmountReceived?: null,
      user?: PromiseOrValue<string> | null
    ): ZapOutEventFilter;
    ZapOut(
      lpToken?: PromiseOrValue<string> | null,
      tokenToReceive?: PromiseOrValue<string> | null,
      lpTokenAmount?: null,
      tokenAmountReceived?: null,
      user?: PromiseOrValue<string> | null
    ): ZapOutEventFilter;
  };

  estimateGas: {
    MAX_INT(overrides?: CallOverrides): Promise<BigNumber>;

    MINIMUM_AMOUNT(overrides?: CallOverrides): Promise<BigNumber>;

    PiraRouter(overrides?: CallOverrides): Promise<BigNumber>;

    WBNB(overrides?: CallOverrides): Promise<BigNumber>;

    estimateZapInRebalancingSwap(
      _token0ToZap: PromiseOrValue<string>,
      _token1ToZap: PromiseOrValue<string>,
      _token0AmountIn: PromiseOrValue<BigNumberish>,
      _token1AmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    estimateZapInSwap(
      _tokenToZap: PromiseOrValue<string>,
      _tokenAmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    estimateZapOutSwap(
      _lpToken: PromiseOrValue<string>,
      _lpTokenAmount: PromiseOrValue<BigNumberish>,
      _tokenToReceive: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxZapReverseRatio(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    recoverWrongTokens(
      _tokenAddress: PromiseOrValue<string>,
      _tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateMaxZapInverseRatio(
      _maxZapInverseRatio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    zapInBNB(
      _lpToken: PromiseOrValue<string>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    zapInBNBRebalancing(
      _token1ToZap: PromiseOrValue<string>,
      _token1AmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      _tokenAmountInMax: PromiseOrValue<BigNumberish>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      _isToken0Sold: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    zapInToken(
      _tokenToZap: PromiseOrValue<string>,
      _tokenAmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    zapInTokenRebalancing(
      _token0ToZap: PromiseOrValue<string>,
      _token1ToZap: PromiseOrValue<string>,
      _token0AmountIn: PromiseOrValue<BigNumberish>,
      _token1AmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      _tokenAmountInMax: PromiseOrValue<BigNumberish>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      _isToken0Sold: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    zapOutBNB(
      _lpToken: PromiseOrValue<string>,
      _lpTokenAmount: PromiseOrValue<BigNumberish>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    zapOutToken(
      _lpToken: PromiseOrValue<string>,
      _tokenToReceive: PromiseOrValue<string>,
      _lpTokenAmount: PromiseOrValue<BigNumberish>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_INT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MINIMUM_AMOUNT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PiraRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WBNB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    estimateZapInRebalancingSwap(
      _token0ToZap: PromiseOrValue<string>,
      _token1ToZap: PromiseOrValue<string>,
      _token0AmountIn: PromiseOrValue<BigNumberish>,
      _token1AmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    estimateZapInSwap(
      _tokenToZap: PromiseOrValue<string>,
      _tokenAmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    estimateZapOutSwap(
      _lpToken: PromiseOrValue<string>,
      _lpTokenAmount: PromiseOrValue<BigNumberish>,
      _tokenToReceive: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxZapReverseRatio(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    recoverWrongTokens(
      _tokenAddress: PromiseOrValue<string>,
      _tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateMaxZapInverseRatio(
      _maxZapInverseRatio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    zapInBNB(
      _lpToken: PromiseOrValue<string>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    zapInBNBRebalancing(
      _token1ToZap: PromiseOrValue<string>,
      _token1AmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      _tokenAmountInMax: PromiseOrValue<BigNumberish>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      _isToken0Sold: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    zapInToken(
      _tokenToZap: PromiseOrValue<string>,
      _tokenAmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    zapInTokenRebalancing(
      _token0ToZap: PromiseOrValue<string>,
      _token1ToZap: PromiseOrValue<string>,
      _token0AmountIn: PromiseOrValue<BigNumberish>,
      _token1AmountIn: PromiseOrValue<BigNumberish>,
      _lpToken: PromiseOrValue<string>,
      _tokenAmountInMax: PromiseOrValue<BigNumberish>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      _isToken0Sold: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    zapOutBNB(
      _lpToken: PromiseOrValue<string>,
      _lpTokenAmount: PromiseOrValue<BigNumberish>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    zapOutToken(
      _lpToken: PromiseOrValue<string>,
      _tokenToReceive: PromiseOrValue<string>,
      _lpTokenAmount: PromiseOrValue<BigNumberish>,
      _tokenAmountOutMin: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
