/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPiraCallee,
  IPiraCalleeInterface,
} from "../../../contracts/interfaces/IPiraCallee";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "piraCall",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPiraCallee__factory {
  static readonly abi = _abi;
  static createInterface(): IPiraCalleeInterface {
    return new utils.Interface(_abi) as IPiraCalleeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPiraCallee {
    return new Contract(address, _abi, signerOrProvider) as IPiraCallee;
  }
}
